version: "3.8"

services:
  router:
    build: ./router
    container_name: router
    cap_add: [NET_ADMIN]
    networks:
      servers: { ipv4_address: 192.168.10.254 }
      clients: { ipv4_address: 192.168.20.254 }
    restart: unless-stopped

  firewall:
    build: ./firewall
    container_name: firewall
    cap_add: [NET_ADMIN]
    depends_on: [router]
    networks:
      servers: { ipv4_address: 192.168.10.253 }
      clients: { ipv4_address: 192.168.20.253 }
    restart: unless-stopped

  dns-server:
    build: ./dns
    container_name: dns-server
    cap_add: [NET_ADMIN]
    depends_on: [router]
    networks:
      servers: { ipv4_address: 192.168.10.10 }
    restart: unless-stopped
    volumes:
      - ./dns/bind:/etc/bind

  dhcp-server:
    build: ./dhcp
    container_name: dhcp-server
    cap_add: [NET_ADMIN]
    depends_on: [router]
    networks:
      clients: { ipv4_address: 192.168.20.252 }
    restart: unless-stopped

  client01:
    image: debian:stable-slim
    container_name: client01
    depends_on:
      - dhcp-server
      - router
      - firewall
      - dns-server
    cap_add:
      - NET_ADMIN
    command: >
      sh -c "
        apt-get update && apt-get install -y isc-dhcp-client &&
        ip link set eth0 up &&
        ip addr flush dev eth0 &&
        dhclient -v eth0 &&
        sleep infinity
      "
    networks:
      clients: {}
    restart: unless-stopped

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    networks:
      servers: { ipv4_address: 192.168.10.20 }
    restart: unless-stopped

  samba-server:
    build: ./samba
    container_name: samba-server
    cap_add: [NET_ADMIN]
    depends_on: [router]
    networks:
      servers: { ipv4_address: 192.168.10.5 }
    restart: unless-stopped
    environment:
      - TZ=America/Sao_Paulo
    volumes:
      - ./samba/smb.conf:/etc/samba/smb.conf
      - ./samba/share:/samba/share
    # ports:
    #   - "139:139"
    #   - "445:445"

networks:
  servers:
    driver: bridge
    ipam:
      config: [{ subnet: 192.168.10.0/24 }]
  clients:
    driver: bridge
    ipam:
      config: [{ subnet: 192.168.20.0/24 }]