FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive

# Instala ferramentas básicas de rede
RUN apt-get update && \
    apt-get install -y \
    iproute2 \
    iputils-ping \
    dnsutils \
    curl \
    net-tools \
    && rm -rf /var/lib/apt/lists/*

# Mantém o container rodando
CMD ["sleep", "infinity"] 